name: Build My Banime40

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build VIAL Firmware
      uses: docker://vialkb/vial-qmk-build:v0.2
      with:
        args: make sporewoh/banime40:default

    - name: Upload Result File
      uses: actions/upload-artifact@v4
      with:
        name: banime40_gaming_firmware
        path: |
          *.hex
          *.bin
          *.uf2
