name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install All Dependencies
      run: |
        sudo apt-get update
        ./util/qmk_install.sh

    - name: Build Only Banime40
      run: |
        make sporewoh/banime40:default
        
    - name: Upload Result File
      uses: actions/upload-artifact@v4
      with:
        name: banime40_gaming_firmware
        path: |
          *.hex
          *.bin
          *.uf2
